import { AvailabilityStatus } from "@prisma/client";
import { COURSE_FORM_FALLBACK, MERCH_FORM_FALLBACK } from "./constants";

export const siteContent = {
  brandName: "UIT Knowledge",
  brandShortName: "UIT",
  slogan: "Tin Mình đi",
  heroTitle: "Ôn các môn trọng tâm ở UIT theo cách gọn, rõ và dễ theo kịp.",
  heroDescription:
    "UIT Knowledge tổng hợp video và khóa học bám sát Giải tích, Đại số tuyến tính, NMLT, OOP, DSA, Mạng máy tính, CSDL và Hệ điều hành. Nội dung được sắp theo từng môn để bạn tra cứu nhanh và ôn tập đúng trọng tâm.",
  heroBadge: "Tài nguyên học tập cho sinh viên UIT",
  introTitle: "Học đúng môn, xem đúng phần cần ôn",
  introDescription:
    "Website tập trung vào các môn đại cương và cơ sở ngành quen thuộc ở UIT, trình bày ngắn gọn để dễ xem lại trước giờ học hoặc trước kỳ thi.",
  aboutTitle: "Nội dung bám sát từng môn học",
  aboutDescription: "Nội dung được sắp theo từng môn để bạn dễ chọn đúng phần đang cần học, ôn giữa kỳ hoặc ôn cuối kỳ.",
  courseFormUrl: COURSE_FORM_FALLBACK,
  merchFormUrl: MERCH_FORM_FALLBACK,
  facebookUrl: "https://www.facebook.com/GenCanyon/",
  zaloPhone: "0971937492",
  contactEmail: "dinh5609@gmail.com",
  address: "",
  footerText: "UIT Knowledge chia sẻ nội dung học tập ngắn gọn, bám môn và dễ theo dõi cho sinh viên UIT.",
  seoTitle: "UIT Knowledge | Video và khóa học cho sinh viên UIT",
  seoDescription: "Video, khóa học và merch của UIT Knowledge cho các môn đại cương và cơ sở ngành tại UIT.",
  youtubeChannelUrl: "",
  studentsCountLabel: "1.5K+ người theo dõi",
  videosCountLabel: "2 video nổi bật",
  coursesCountLabel: "3 khóa học giới thiệu",
  merchCountLabel: "3 sản phẩm merch",
  showFeaturedVideos: true,
  showFeaturedCourses: true,
  showFeaturedProducts: true,
  showTestimonials: true,
  showFaq: true,
};

export const demoCourses = [
  {
    title: "Giải tích và Đại số tuyến tính cho sinh viên UIT",
    slug: "giai-tich-dai-so-tuyen-tinh-uit",
    category: "Đại cương",
    level: "Cơ bản",
    format: "Online",
    shortDescription: "Hệ thống lại các phần quan trọng để sinh viên dễ ôn giữa kỳ, cuối kỳ và học chắc từ gốc.",
    longDescription:
      "Khóa học tập trung vào các ý quan trọng của Giải tích và Đại số tuyến tính, trình bày ngắn gọn để người học nắm nhanh cách làm và cách ôn tập.",
    targetAudience: "Sinh viên UIT đang học Giải tích, Đại số tuyến tính hoặc muốn ôn lại nền tảng toán.",
    outline: "Giới hạn; Đạo hàm; Tích phân; Ma trận; Định thức; Hệ phương trình tuyến tính; Vector và không gian vector.",
    featuredPoints: ["Bám sát môn trên lớp", "Dễ ôn lại trước kỳ thi", "Tóm tắt ngắn gọn, dễ theo dõi"],
    priceLabel: "Liên hệ để nhận tư vấn",
    originalPriceLabel: "Mở theo từng đợt",
    durationLabel: "6 tuần",
    featured: true,
    sortOrder: 1,
    tags: ["giai-tich", "dai-so-tuyen-tinh", "toan"],
  },
  {
    title: "NMLT, OOP và DSA nền tảng",
    slug: "nmlt-oop-dsa-nen-tang",
    category: "Lập trình",
    level: "Cơ bản đến nâng cao",
    format: "Online",
    shortDescription: "Đi từ tư duy lập trình cơ bản đến cấu trúc dữ liệu và giải thuật theo cách sinh viên UIT dễ theo kịp.",
    longDescription:
      "Khóa học gom các phần quan trọng của NMLT, OOP và DSA thành một lộ trình rõ ràng để người học nắm chắc nền tảng trước khi học sâu hơn.",
    targetAudience: "Sinh viên năm nhất, năm hai hoặc người cần học lại nền tảng lập trình.",
    outline: "Biến và hàm; Mảng và chuỗi; Con trỏ cơ bản; Lớp và đối tượng; Stack; Queue; Tree; Graph; Độ phức tạp.",
    featuredPoints: ["Lộ trình rõ ràng", "Bám môn học ở UIT", "Phù hợp để ôn và học lại từ đầu"],
    priceLabel: "Liên hệ để nhận tư vấn",
    originalPriceLabel: "Mở theo từng đợt",
    durationLabel: "8 tuần",
    featured: true,
    sortOrder: 2,
    tags: ["nmlt", "oop", "dsa"],
  },
  {
    title: "Mạng máy tính, CSDL và Hệ điều hành căn bản",
    slug: "mang-csdl-he-dieu-hanh-can-ban",
    category: "Cơ sở ngành",
    level: "Nền tảng",
    format: "Online",
    shortDescription: "Ôn các ý cốt lõi của ba môn nền tảng theo hướng dễ nhớ, dễ liên hệ với bài học trên lớp.",
    longDescription:
      "Khóa học tập trung vào các khái niệm cốt lõi của Mạng máy tính, CSDL và Hệ điều hành để sinh viên nắm đúng phần thường gặp trong quá trình học.",
    targetAudience: "Sinh viên UIT đang học các môn cơ sở ngành hoặc cần hệ thống lại kiến thức trước kỳ thi.",
    outline: "TCP/IP và subnet; Mô hình dữ liệu quan hệ; SQL cơ bản; Tiến trình; Bộ nhớ; Đồng bộ.",
    featuredPoints: ["Giải thích ngắn gọn", "Bám trọng tâm môn học", "Dễ xem lại trước giờ kiểm tra"],
    priceLabel: "Liên hệ để nhận tư vấn",
    originalPriceLabel: "Mở theo từng đợt",
    durationLabel: "6 tuần",
    featured: true,
    sortOrder: 3,
    tags: ["mang-may-tinh", "csdl", "he-dieu-hanh"],
  },
];

export const demoProducts = [
  {
    title: "Áo thun UIT Knowledge",
    slug: "ao-thun-uit-knowledge",
    category: "Áo",
    shortDescription: "Áo thun tối giản, dễ mặc hằng ngày và giữ tinh thần thương hiệu UIT Knowledge.",
    longDescription: "Form áo gọn gàng, hợp sinh viên, phối logo trắng đen nổi bật trên nền sáng hiện đại.",
    material: "Cotton 2 chiều",
    variantText: "Size S, M, L, XL",
    price: "219000",
    compareAtPrice: "269000",
    availabilityStatus: AvailabilityStatus.IN_STOCK,
    featured: true,
    sortOrder: 1,
    tags: ["ao", "merch", "uit"],
  },
  {
    title: "Móc khóa UIT Knowledge",
    slug: "moc-khoa-uit-knowledge",
    category: "Phụ kiện",
    shortDescription: "Móc khóa nhỏ gọn, dễ mang theo và tạo điểm nhấn nhận diện thương hiệu.",
    longDescription: "Sản phẩm phù hợp làm quà tặng hoặc decor balo, gợi cảm giác tối giản và đậm chất công nghệ.",
    material: "Acrylic cứng",
    variantText: "Phiên bản logo trắng đen",
    price: "49000",
    compareAtPrice: "59000",
    availabilityStatus: AvailabilityStatus.IN_STOCK,
    featured: true,
    sortOrder: 2,
    tags: ["moc-khoa", "badge", "phu-kien"],
  },
  {
    title: "Dây đeo thẻ UIT Knowledge",
    slug: "day-deo-the-uit-knowledge",
    category: "Phụ kiện",
    shortDescription: "Dây đeo thẻ đơn giản, tiện dụng cho sinh viên và người đi workshop.",
    longDescription: "Thiết kế gọn, chất liệu bền, phù hợp dùng với thẻ sinh viên, sự kiện hoặc quà tặng cộng đồng.",
    material: "Polyester dệt",
    variantText: "Màu đen phối logo trắng",
    price: "69000",
    compareAtPrice: "79000",
    availabilityStatus: AvailabilityStatus.LIMITED,
    featured: true,
    sortOrder: 3,
    tags: ["day-deo", "uit", "phu-kien"],
  },
];

export const demoVideos = [
  {
    title: "Bắt đầu ôn các môn nền tảng ở UIT như thế nào?",
    slug: "bat-dau-on-cac-mon-nen-tang-o-uit",
    youtubeUrl: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
    shortDescription: "Video tham khảo về cách sắp thứ tự ôn tập các môn nền tảng và cơ sở ngành cho sinh viên UIT.",
    durationLabel: "4:26:00",
    featured: true,
    sortOrder: 1,
    tags: ["giai-tich", "nmlt", "dsa"],
  },
  {
    title: "Mạng máy tính, CSDL và Hệ điều hành: phần cốt lõi cần nhớ",
    slug: "mang-csdl-he-dieu-hanh-cot-loi",
    youtubeUrl: "https://www.youtube.com/watch?v=qiQR5rTSshw",
    shortDescription: "Video tham khảo để xem nhanh các ý quan trọng của nhóm môn cơ sở ngành trước giờ học hoặc trước kỳ thi.",
    durationLabel: "1:10:00",
    featured: true,
    sortOrder: 2,
    tags: ["mang-may-tinh", "csdl", "he-dieu-hanh"],
  },
];

export const demoTestimonials = [
  {
    name: "Nguyễn Minh Trí",
    roleLabel: "Sinh viên UIT",
    quote: "Mình dễ ôn lại Giải tích và Đại số tuyến tính hơn vì nội dung được chia ngắn, đi thẳng vào phần hay quên.",
    courseLabel: "Giải tích và Đại số tuyến tính cho sinh viên UIT",
    featured: true,
    sortOrder: 1,
  },
  {
    name: "Lê Trần Khánh Vy",
    roleLabel: "Sinh viên năm hai",
    quote: "Phần NMLT, OOP và DSA được hệ thống rất gọn, nhìn vào là biết nên học gì trước và ôn gì sau.",
    courseLabel: "NMLT, OOP và DSA nền tảng",
    featured: true,
    sortOrder: 2,
  },
];

export const demoFaqs = [
  {
    question: "Mình có cần tạo tài khoản để xem nội dung không?",
    answer: "Không. Website mở công khai cho người xem, chỉ khu vực admin mới cần đăng nhập.",
    category: "Chung",
    featured: true,
    sortOrder: 1,
  },
  {
    question: "Khi đăng ký khóa học thì thanh toán ở đâu?",
    answer: "Ở phiên bản hiện tại, nút đăng ký sẽ mở Google Form để UIT Knowledge tiếp nhận thông tin và tư vấn tiếp.",
    category: "Khóa học",
    featured: true,
    sortOrder: 2,
  },
  {
    question: "Merch có nhiều size hoặc biến thể không?",
    answer: "Thông tin biến thể được ghi ngay ở từng trang sản phẩm và form mua merch sẽ thu thập lựa chọn chi tiết.",
    category: "Merch",
    featured: true,
    sortOrder: 3,
  },
];
