INSERT INTO "SiteSetting" (
  "id",
  "brandName",
  "brandShortName",
  "slogan",
  "heroTitle",
  "heroDescription",
  "heroBadge",
  "introTitle",
  "introDescription",
  "aboutTitle",
  "aboutDescription",
  "courseFormUrl",
  "merchFormUrl",
  "facebookUrl",
  "zaloPhone",
  "contactEmail",
  "address",
  "footerText",
  "seoTitle",
  "seoDescription",
  "youtubeChannelUrl",
  "studentsCountLabel",
  "videosCountLabel",
  "coursesCountLabel",
  "merchCountLabel",
  "showFeaturedVideos",
  "showFeaturedCourses",
  "showFeaturedProducts",
  "showTestimonials",
  "showFaq",
  "createdAt",
  "updatedAt"
)
VALUES (
  'site',
  'UIT Knowledge',
  'UIT',
  'Tin Mình đi',
  'Ôn các môn trọng tâm ở UIT theo cách gọn, rõ và dễ theo kịp.',
  'UIT Knowledge tổng hợp video và khóa học bám sát Giải tích, Đại số tuyến tính, NMLT, OOP, DSA, Mạng máy tính, CSDL và Hệ điều hành. Nội dung được sắp theo từng môn để bạn tra cứu nhanh và ôn tập đúng trọng tâm.',
  'Tài nguyên học tập cho sinh viên UIT',
  'Học đúng môn, xem đúng phần cần ôn',
  'Website tập trung vào các môn đại cương và cơ sở ngành quen thuộc ở UIT, trình bày ngắn gọn để dễ xem lại trước giờ học hoặc trước kỳ thi.',
  'Nội dung bám sát từng môn học',
  'Nội dung được sắp theo từng môn để bạn dễ chọn đúng phần đang cần học, ôn giữa kỳ hoặc ôn cuối kỳ.',
  'https://docs.google.com/forms/d/e/1FAIpQLSdY0Asoch6Q1A4IgaUdEEmELoSXwnapd7xh5H6gwlihOGE2Xg/viewform',
  'https://docs.google.com/forms/d/e/1FAIpQLSf_bZqeadfGiGed5aDlwoAF2eGl-wy_K5WlCHybsDe1sV_q5g/viewform',
  'https://www.facebook.com/GenCanyon/',
  '0971937492',
  'dinh5609@gmail.com',
  '',
  'UIT Knowledge chia sẻ nội dung học tập ngắn gọn, bám môn và dễ theo dõi cho sinh viên UIT.',
  'UIT Knowledge | Video và khóa học cho sinh viên UIT',
  'Video, khóa học và merch của UIT Knowledge cho các môn đại cương và cơ sở ngành tại UIT.',
  '',
  '1.5K+ người theo dõi',
  '2 video nổi bật',
  '3 khóa học giới thiệu',
  '3 sản phẩm merch',
  true,
  true,
  true,
  true,
  true,
  NOW(),
  NOW()
)
ON CONFLICT ("id") DO UPDATE SET
  "brandName" = EXCLUDED."brandName",
  "brandShortName" = EXCLUDED."brandShortName",
  "slogan" = EXCLUDED."slogan",
  "heroTitle" = EXCLUDED."heroTitle",
  "heroDescription" = EXCLUDED."heroDescription",
  "heroBadge" = EXCLUDED."heroBadge",
  "introTitle" = EXCLUDED."introTitle",
  "introDescription" = EXCLUDED."introDescription",
  "aboutTitle" = EXCLUDED."aboutTitle",
  "aboutDescription" = EXCLUDED."aboutDescription",
  "footerText" = EXCLUDED."footerText",
  "seoTitle" = EXCLUDED."seoTitle",
  "seoDescription" = EXCLUDED."seoDescription",
  "studentsCountLabel" = EXCLUDED."studentsCountLabel",
  "videosCountLabel" = EXCLUDED."videosCountLabel",
  "coursesCountLabel" = EXCLUDED."coursesCountLabel",
  "merchCountLabel" = EXCLUDED."merchCountLabel",
  "updatedAt" = NOW();
